import { Link } from "react-router-dom";
import { 
  ArrowLeft, 
  Layout, 
  List, 
  Calendar, 
  CreditCard, 
  Send, 
  CheckCircle, 
  Repeat,
  Clock,
  BookOpen,
  HelpCircle,
  ChevronRight,
  FileText,
  Users
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";

const InvoicesGuide = () => {
  const sections = [
    {
      id: "templates",
      icon: Layout,
      title: "Creating Custom Invoice Templates",
      content: [
        "Go to Invoicing → Templates → New Template.",
        "Choose a style layout (Classic, Modern, Minimal).",
        "Add your business logo, colors, and branding.",
        "Choose which fields to show (Invoice #, PO #, Client Info, Notes).",
        "Save your template so you can reuse it for all future invoices.",
        "Set a default template if you only use one style."
      ]
    },
    {
      id: "line-items",
      icon: List,
      title: "Adding Line Items, Taxes & Discounts",
      content: [
        "Click Create New Invoice.",
        "Add a line item by entering description, quantity, and rate.",
        "Select a category (Service, Product, Labor, Subscription).",
        "Add tax by selecting a tax rate from your tax settings.",
        "Add a discount (percentage or fixed amount).",
        "Review calculations and totals before saving."
      ]
    },
    {
      id: "payment-terms",
      icon: Calendar,
      title: "Setting Payment Terms & Due Dates",
      content: [
        "Open the invoice settings section.",
        "Choose payment terms (Due on Receipt, Net 7, Net 15, Net 30, Custom).",
        "Adjust the due date if needed.",
        "Add late-fee rules (optional).",
        "Insert notes or instructions for the client (e.g., payment reminders, bank details).",
        "Save the invoice."
      ]
    },
    {
      id: "online-payments",
      icon: CreditCard,
      title: "Adding Online Payment Links",
      content: [
        "Connect your payment provider under Settings → Payments (ex: Stripe, PayPal).",
        "Enable online payments for invoices.",
        "Choose which methods are allowed: Credit/Debit, ACH, Bank Transfer.",
        "Add the payment button/link automatically generated by the system.",
        "Preview the invoice to ensure the payment link appears.",
        "Save for sending."
      ]
    },
    {
      id: "sending",
      icon: Send,
      title: "Sending Invoices via Email or PDF",
      content: [
        "Click Send Invoice from the invoice preview page.",
        "Choose Email or Download PDF.",
        "For email sending: Enter the client's email, add a subject line, add a message or choose a template.",
        "The system tracks delivery and opens automatically.",
        "For PDF: save or print the exported file.",
        "The invoice status changes to Sent once delivered."
      ]
    },
    {
      id: "status-tracking",
      icon: CheckCircle,
      title: "Tracking Invoice Status (Sent, Viewed, Paid)",
      content: [
        "View all invoice statuses under Invoicing → All Invoices.",
        "Statuses include: Draft, Sent, Viewed, Partially Paid, Paid, Overdue.",
        "Open each invoice to see: Date sent, Date viewed, Payment activity.",
        "Set automated reminders for unpaid invoices.",
        "Mark invoices as paid manually if payment was made offline."
      ]
    },
    {
      id: "recurring",
      icon: Repeat,
      title: "Automating Recurring Invoices",
      content: [
        "Go to Invoicing → Recurring Templates → New Recurring Invoice.",
        "Choose the client and invoice template.",
        "Set the billing frequency (Weekly, Monthly, Quarterly, Yearly).",
        "Enable auto-send for hands-free billing.",
        "Enable auto-charge if supported by your payment provider.",
        "Review the schedule and activate it."
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Breadcrumbs */}
        <nav className="flex items-center gap-2 text-sm text-muted-foreground mb-6">
          <Link to="/resources" className="hover:text-foreground transition-colors">
            Resources
          </Link>
          <ChevronRight className="h-4 w-4" />
          <Link to="/resources" className="hover:text-foreground transition-colors">
            Guides & Tutorials
          </Link>
          <ChevronRight className="h-4 w-4" />
          <span className="text-foreground font-medium">How to Create & Send Invoices</span>
        </nav>

        {/* Back Button */}
        <Link to="/resources">
          <Button variant="ghost" className="mb-6 -ml-2 gap-2">
            <ArrowLeft className="h-4 w-4" />
            Back to Resources
          </Button>
        </Link>

        {/* Header Card */}
        <Card className="mb-8 border-primary/20 bg-gradient-to-br from-primary/5 to-background">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center">
                <FileText className="h-6 w-6 text-primary" />
              </div>
              <div>
                <CardTitle className="text-2xl md:text-3xl font-bold">
                  How to Create & Send Invoices
                </CardTitle>
              </div>
            </div>
            <div className="flex flex-wrap gap-3">
              <Badge variant="secondary" className="gap-1.5">
                <BookOpen className="h-3 w-3" />
                Invoicing
              </Badge>
              <Badge variant="outline" className="gap-1.5">
                <Clock className="h-3 w-3" />
                10 minutes read
              </Badge>
            </div>
          </CardHeader>
        </Card>

        {/* Overview Section */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="text-lg font-semibold">Overview</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground leading-relaxed">
              Master the invoicing process with this complete walkthrough. Learn how to create 
              professional invoices, add payment options, and send them to clients effortlessly.
            </p>
          </CardContent>
        </Card>

        {/* Accordion Sections */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="text-lg font-semibold">Step-by-Step Instructions</CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <Accordion type="single" collapsible className="w-full space-y-2">
              {sections.map((section, index) => (
                <AccordionItem 
                  key={section.id} 
                  value={section.id}
                  className="border rounded-lg px-4 data-[state=open]:bg-muted/30 transition-colors"
                >
                  <AccordionTrigger className="hover:no-underline py-4">
                    <div className="flex items-center gap-3">
                      <div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                        <section.icon className="h-5 w-5 text-primary" />
                      </div>
                      <div className="text-left">
                        <span className="text-xs text-muted-foreground font-medium">
                          Step {index + 1}
                        </span>
                        <h3 className="font-semibold text-sm md:text-base">
                          {section.title}
                        </h3>
                      </div>
                    </div>
                  </AccordionTrigger>
                  <AccordionContent className="pb-4">
                    <div className="ml-12 space-y-3">
                      <ol className="space-y-3">
                        {section.content.map((item, idx) => (
                          <li 
                            key={idx} 
                            className="flex items-start gap-3 text-muted-foreground"
                          >
                            <span className="h-6 w-6 rounded-full bg-primary/10 text-primary text-xs font-semibold flex items-center justify-center shrink-0 mt-0.5">
                              {idx + 1}
                            </span>
                            <span className="leading-relaxed">{item}</span>
                          </li>
                        ))}
                      </ol>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </CardContent>
        </Card>

        {/* Perfect For Section */}
        <Card className="mb-8 border-green-500/20 bg-gradient-to-br from-green-500/5 to-background">
          <CardHeader>
            <CardTitle className="text-lg font-semibold flex items-center gap-2">
              <Users className="h-5 w-5 text-green-500" />
              Perfect For
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground leading-relaxed">
              Businesses that want fast, automated, and professional billing.
            </p>
          </CardContent>
        </Card>

        {/* Need Help Section */}
        <Card className="bg-muted/30 border-dashed">
          <CardContent className="py-6">
            <div className="flex flex-col sm:flex-row items-center gap-4 text-center sm:text-left">
              <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                <HelpCircle className="h-6 w-6 text-primary" />
              </div>
              <div className="flex-1">
                <h3 className="font-semibold mb-1">Need help?</h3>
                <p className="text-sm text-muted-foreground">
                  Can't find what you're looking for? Our support team is here to assist you.
                </p>
              </div>
              <Button variant="outline" className="gap-2 shrink-0">
                Contact Support
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default InvoicesGuide;
