import { useState } from "react";
import { motion } from "framer-motion";
import { Header } from "@/components/Header";
import { useNavigate } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { 
  ArrowLeft, 
  Mail, 
  Clock, 
  Send,
  CheckCircle,
  HelpCircle,
  FileText,
  AlertCircle
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

const ContactSupport = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { user } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [ticketNumber, setTicketNumber] = useState("");
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    category: "",
    priority: "",
    subject: "",
    message: ""
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    try {
      const { data, error } = await supabase
        .from('support_tickets')
        .insert({
          user_id: user?.id || null,
          name: formData.name,
          email: formData.email,
          category: formData.category,
          priority: formData.priority || 'medium',
          subject: formData.subject,
          message: formData.message,
          ticket_number: 'TEMP' // Will be auto-generated by trigger
        })
        .select('ticket_number')
        .single();

      if (error) throw error;

      setTicketNumber(data.ticket_number);
      setSubmitted(true);
      toast({
        title: "Support ticket submitted",
        description: `Your ticket ${data.ticket_number} has been created. We'll get back to you within 24 hours.`,
      });
    } catch (error: any) {
      console.error('Error submitting ticket:', error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to submit support ticket. Please try again.",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const contactMethods = [
    {
      title: "Email Support",
      description: "Get help via email within 24 hours",
      icon: Mail,
      action: "support@majrbooks.com",
      availability: "24/7 Response",
    },
  ];

  const categories = [
    { value: "billing", label: "Billing & Subscriptions" },
    { value: "technical", label: "Technical Issue" },
    { value: "feature", label: "Feature Request" },
    { value: "account", label: "Account & Login" },
    { value: "integration", label: "Integration Help" },
    { value: "other", label: "Other" },
  ];

  const priorities = [
    { value: "low", label: "Low - General question", color: "bg-blue-500" },
    { value: "medium", label: "Medium - Issue affecting work", color: "bg-yellow-500" },
    { value: "high", label: "High - Business critical", color: "bg-orange-500" },
    { value: "urgent", label: "Urgent - System down", color: "bg-red-500" },
  ];

  if (submitted) {
    return (
      <div className="min-h-screen bg-background text-foreground">
        <Header navigate={navigate} />
        <section className="pt-32 pb-16 px-6">
          <div className="container mx-auto max-w-2xl">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5 }}
            >
              <Card className="text-center p-12">
                <div className="bg-primary/10 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6">
                  <CheckCircle className="h-10 w-10 text-primary" />
                </div>
                <h2 className="text-3xl font-bold mb-4">Request Submitted!</h2>
                <p className="text-muted-foreground mb-2">
                  Your support ticket has been created successfully.
                </p>
                <p className="text-muted-foreground mb-8">
                  Ticket #: <span className="font-mono font-semibold">{ticketNumber}</span>
                </p>
                <div className="bg-muted/50 rounded-lg p-4 mb-8">
                  <p className="text-sm text-muted-foreground">
                    Expected response time: <span className="font-semibold text-foreground">Within 24 hours</span>
                  </p>
                </div>
                <div className="flex justify-center gap-4">
                  <Button variant="outline" onClick={() => setSubmitted(false)}>
                    Submit Another Request
                  </Button>
                  <Button onClick={() => navigate("/resources")}>
                    Back to Resources
                  </Button>
                </div>
              </Card>
            </motion.div>
          </div>
        </section>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background text-foreground">
      <Header navigate={navigate} />

      <section className="pt-32 pb-16 px-6">
        <div className="container mx-auto max-w-5xl">
          <Button
            variant="ghost"
            onClick={() => navigate("/resources")}
            className="mb-6 gap-2"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Resources
          </Button>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="flex items-center gap-4 mb-6">
              <div className="bg-primary/10 p-4 rounded-xl">
                <Mail className="h-10 w-10 text-primary" />
              </div>
              <div>
                <h1 className="text-4xl font-bold">Contact Support</h1>
                <p className="text-muted-foreground mt-2">
                  We're here to help. Choose how you'd like to reach us.
                </p>
              </div>
            </div>

            {/* Contact Methods */}
            <div className="grid md:grid-cols-3 gap-4 mb-10">
              {contactMethods.map((method, idx) => (
                <Card key={idx} className="hover:shadow-lg transition-all hover:-translate-y-1 cursor-pointer">
                  <CardContent className="p-6">
                    <div className="bg-primary/10 p-3 rounded-lg w-fit mb-4">
                      <method.icon className="h-6 w-6 text-primary" />
                    </div>
                    <h3 className="font-semibold mb-1">{method.title}</h3>
                    <p className="text-sm text-muted-foreground mb-3">{method.description}</p>
                    <p className="font-medium text-primary text-sm">{method.action}</p>
                    <div className="flex items-center gap-1 mt-2 text-xs text-muted-foreground">
                      <Clock className="h-3 w-3" />
                      {method.availability}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>

            <div className="grid lg:grid-cols-3 gap-8">
              {/* Support Form */}
              <div className="lg:col-span-2">
                <Card>
                  <CardHeader>
                    <CardTitle>Submit a Support Request</CardTitle>
                    <CardDescription>
                      Fill out the form below and we'll get back to you as soon as possible.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <form onSubmit={handleSubmit} className="space-y-6">
                      <div className="grid md:grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label htmlFor="name">Full Name</Label>
                          <Input
                            id="name"
                            placeholder="John Doe"
                            value={formData.name}
                            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                            required
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="email">Email Address</Label>
                          <Input
                            id="email"
                            type="email"
                            placeholder="john@example.com"
                            value={formData.email}
                            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                            required
                          />
                        </div>
                      </div>

                      <div className="grid md:grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label htmlFor="category">Category</Label>
                          <Select
                            value={formData.category}
                            onValueChange={(value) => setFormData({ ...formData, category: value })}
                          >
                            <SelectTrigger>
                              <SelectValue placeholder="Select a category" />
                            </SelectTrigger>
                            <SelectContent>
                              {categories.map((cat) => (
                                <SelectItem key={cat.value} value={cat.value}>
                                  {cat.label}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="priority">Priority</Label>
                          <Select
                            value={formData.priority}
                            onValueChange={(value) => setFormData({ ...formData, priority: value })}
                          >
                            <SelectTrigger>
                              <SelectValue placeholder="Select priority" />
                            </SelectTrigger>
                            <SelectContent>
                              {priorities.map((pri) => (
                                <SelectItem key={pri.value} value={pri.value}>
                                  <span className="flex items-center gap-2">
                                    <span className={`w-2 h-2 rounded-full ${pri.color}`} />
                                    {pri.label}
                                  </span>
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="subject">Subject</Label>
                        <Input
                          id="subject"
                          placeholder="Brief description of your issue"
                          value={formData.subject}
                          onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                          required
                        />
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="message">Message</Label>
                        <Textarea
                          id="message"
                          placeholder="Please describe your issue in detail. Include any error messages, steps to reproduce, and what you've already tried."
                          rows={6}
                          value={formData.message}
                          onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                          required
                        />
                      </div>

                      <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <AlertCircle className="h-4 w-4" />
                        <span>Attach screenshots or files after submitting via the confirmation email.</span>
                      </div>

                      <Button type="submit" className="w-full gap-2" disabled={isSubmitting}>
                        {isSubmitting ? (
                          <>Submitting...</>
                        ) : (
                          <>
                            <Send className="h-4 w-4" />
                            Submit Request
                          </>
                        )}
                      </Button>
                    </form>
                  </CardContent>
                </Card>
              </div>

              {/* Sidebar */}
              <div className="space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">Before You Contact Us</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div
                      className="flex items-start gap-3 cursor-pointer hover:text-primary transition-colors"
                      onClick={() => navigate("/resources/faqs")}
                    >
                      <HelpCircle className="h-5 w-5 text-muted-foreground shrink-0 mt-0.5" />
                      <div>
                        <p className="font-medium">Check our FAQs</p>
                        <p className="text-sm text-muted-foreground">Quick answers to common questions</p>
                      </div>
                    </div>
                    <div
                      className="flex items-start gap-3 cursor-pointer hover:text-primary transition-colors"
                      onClick={() => navigate("/resources/troubleshooting")}
                    >
                      <FileText className="h-5 w-5 text-muted-foreground shrink-0 mt-0.5" />
                      <div>
                        <p className="font-medium">Troubleshooting Guide</p>
                        <p className="text-sm text-muted-foreground">Step-by-step problem solving</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card className="bg-muted/50">
                  <CardContent className="p-6">
                    <h3 className="font-semibold mb-2">Support Hours</h3>
                    <div className="space-y-2 text-sm">
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Email</span>
                        <span>24/7</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card className="bg-gradient-to-br from-primary/10 to-primary/5 border-primary/20">
                  <CardContent className="p-6">
                    <Badge className="mb-3">Priority Support</Badge>
                    <h3 className="font-semibold mb-2">Need faster help?</h3>
                    <p className="text-sm text-muted-foreground mb-4">
                      Enterprise customers get 24/7 priority support with dedicated account managers.
                    </p>
                    <Button variant="outline" size="sm" className="w-full">
                      Learn About Enterprise
                    </Button>
                  </CardContent>
                </Card>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default ContactSupport;
