-- Add detailed tax return fields to tax_returns table
ALTER TABLE public.tax_returns
ADD COLUMN wages NUMERIC DEFAULT 0,
ADD COLUMN business_income NUMERIC DEFAULT 0,
ADD COLUMN investment_income NUMERIC DEFAULT 0,
ADD COLUMN other_income NUMERIC DEFAULT 0,
ADD COLUMN total_income NUMERIC DEFAULT 0,
ADD COLUMN standard_deduction NUMERIC DEFAULT 0,
ADD COLUMN itemized_deductions NUMERIC DEFAULT 0,
ADD COLUMN mortgage_interest NUMERIC DEFAULT 0,
ADD COLUMN charitable_contributions NUMERIC DEFAULT 0,
ADD COLUMN state_local_taxes NUMERIC DEFAULT 0,
ADD COLUMN medical_expenses NUMERIC DEFAULT 0,
ADD COLUMN total_deductions NUMERIC DEFAULT 0,
ADD COLUMN child_tax_credit NUMERIC DEFAULT 0,
ADD COLUMN education_credits NUMERIC DEFAULT 0,
ADD COLUMN other_credits NUMERIC DEFAULT 0,
ADD COLUMN total_credits NUMERIC DEFAULT 0,
ADD COLUMN adjusted_gross_income NUMERIC DEFAULT 0,
ADD COLUMN taxable_income NUMERIC DEFAULT 0,
ADD COLUMN total_tax NUMERIC DEFAULT 0,
ADD COLUMN federal_withholding NUMERIC DEFAULT 0,
ADD COLUMN estimated_payments NUMERIC DEFAULT 0,
ADD COLUMN refund_amount NUMERIC DEFAULT 0,
ADD COLUMN amount_owed NUMERIC DEFAULT 0;